### ISSUE TITLE
make doc fails

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/SingularInterface#25]
The Makefile assumes that $(GAPROOT)/bin/gap.sh is the final script to launch GAP. In my case it is not, since I have my packages elsewhere, i.e., not under $(GAPROOT)/pkg

**Comment by fingolfin** [comment]
Solution here is to not use `make doc` (which I just removed), simply launch the `makedoc.g` script with the appropriate `gap` executable.
