### ISSUE TITLE
Migrating to gap-packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/SingularInterface#59]
We have created new VO at https://github.com/gap-packages and suggest that all GAP packages could eventually migrate there - please consider doing so when it may be appropriate and less disruptive for your package.

**Comment by alex-konovalov** [comment]
Migrated to https://github.com/gap-packages/SingularInterface

**Comment by mohamed-barakat** [comment]
The link

http://gap-system.github.io/SingularInterface/

which appears on

https://github.com/gap-packages/SingularInterface

is broken.

**Comment by alex-konovalov** [comment]
@mohamed-barakat Thanks - updated.
